### ISSUE TITLE
Can't load the SageMaker Endpoint

### ISSUE THREAD

**Issue by vuhondat** [aws-samples/amazon-sagemaker-inference-client#11]
Hi Team,

I've just deploy this repo.
I'm facing with the error "ERROR: An error occurred retrieving the selected regions SageMaker Endpoints:
Error: Network Error"
![image](https://user-images.githubusercontent.com/12470007/137511939-ea04f506-6fbe-4409-b5ef-e28a0c3b143c.png)

Kindly check and advice.

Thanks so much!

Vu Pham

**Comment by dcolcott** [comment]
Thanks Vu Pham,

You need to select a Sagemaker Endpoint from the Endpoint name List. This will automatically populate based on the Endpoints you have in the selected region. If there is none available, make sure you have the right region selected.
